# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(170, 30, 269, 318))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.filename = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.filename.setObjectName("filename")
        self.verticalLayout.addWidget(self.filename)
        self.Error_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Error_label.setText("")
        self.Error_label.setObjectName("Error_label")
        self.verticalLayout.addWidget(self.Error_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.review = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.review.setObjectName("review")
        self.verticalLayout_2.addWidget(self.review)
        self.solve = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.solve.setObjectName("solve")
        self.verticalLayout_2.addWidget(self.solve)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.kmethod = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.kmethod.setChecked(True)
        self.kmethod.setObjectName("kmethod")
        self.horizontalLayout_3.addWidget(self.kmethod)
        self.set_k = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.set_k.setMinimum(1)
        self.set_k.setMaximum(999)
        self.set_k.setDisplayIntegerBase(10)
        self.set_k.setObjectName("set_k")
        self.horizontalLayout_3.addWidget(self.set_k)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.single = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.single.setObjectName("single")
        self.verticalLayout_3.addWidget(self.single)
        self.complete = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.complete.setObjectName("complete")
        self.verticalLayout_3.addWidget(self.complete)
        self.average = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.average.setObjectName("average")
        self.verticalLayout_3.addWidget(self.average)
        self.weighted = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.weighted.setObjectName("weighted")
        self.verticalLayout_3.addWidget(self.weighted)
        self.centroid = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.centroid.setObjectName("centroid")
        self.verticalLayout_3.addWidget(self.centroid)
        self.median = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.median.setObjectName("median")
        self.verticalLayout_3.addWidget(self.median)
        self.ward = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.ward.setObjectName("ward")
        self.verticalLayout_3.addWidget(self.ward)
        self.newmethod = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.newmethod.setObjectName("newmethod")
        self.verticalLayout_3.addWidget(self.newmethod)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.gridLayoutWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Введите имя файла"))
        self.review.setText(_translate("MainWindow", "Обзор"))
        self.solve.setText(_translate("MainWindow", "Рассчитать"))
        self.label_2.setText(_translate("MainWindow", "Выберите метод кластеризации"))
        self.kmethod.setText(_translate("MainWindow", "Метод k-средних"))
        self.single.setText(_translate("MainWindow", "single"))
        self.complete.setText(_translate("MainWindow", "complete"))
        self.average.setText(_translate("MainWindow", "average"))
        self.weighted.setText(_translate("MainWindow", "weighted"))
        self.centroid.setText(_translate("MainWindow", "centroid"))
        self.median.setText(_translate("MainWindow", "median"))
        self.ward.setText(_translate("MainWindow", "ward"))
        self.newmethod.setText(_translate("MainWindow", "DBSCAN"))
